name: facebook_auth_desktop
description: macOS support for flutter_facebook_auth
version: 1.0.1
publish_to: 'none'
homepage:

environment:
  sdk: ">=2.18.1 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  flutter_secure_storage: ^9.0.0
  flutter_facebook_auth_platform_interface: 
    git: 
      url: git@github.com:fastworkco/fw-flutter-facebook-auth.git
      ref: 6d6eba0499dd1ab6338abef6fe33aff1128ae454
      path: facebook_auth_platform_interface


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    implements: flutter_facebook_auth
    platforms:
      macos:
        pluginClass: FacebookAuthDesktopPlugin
        dartPluginClass: FacebookAuthDesktopPlugin